name: Build
on:
  push:
    branches-ignore: [debian]

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} / Redmine ${{ matrix.redmine }}
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        ruby: ["2.6"]
        redmine: ["4.1.0"]
      fail-fast: false

    env:
      REDMINE_VERSION: ${{ matrix.redmine }}

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v1
        with:
          path: vendor
          key: v1-ruby-${{ matrix.ruby }}-redmine-${{ matrix.redmine }}

      - name: Install dependencies
        run: |
          sudo apt-get update --yes --quiet
          sudo apt-get install --yes --quiet postgresql libpq-dev subversion
          sudo -u postgres createuser -s runner

      - name: Install bundler
        run: |
          gem install bundler -v '~> 2.0'
          bundle config path "$(pwd)/vendor/bundle"

      - name: Install ruby dependencies
        run: bundle install --jobs=4 --retry=3 --without development

      - name: Install node dependencies
        run: npm ci --cache vendor/npm

      - name: Install redmine ${{ matrix.redmine }}
        run: ./redmine update

      - name: Build frontend assets
        run: npm run build

      - name: Run rspec spec/plugin
        run: bundle exec rspec spec/plugin --color

      - name: Run rspec spec/browser
        run: bundle exec rspec spec/browser --color
